version: '3'
services:
  my_portfolio_v2:
    container_name: my_portfolio_web_v2
    image: my_portfolio_web_v2
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - my-portfolio-v2-node-modules:/app/node_modules
volumes:
  my-portfolio-v2-node-modules: null
